import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/dist/client/router'
import Example from '../components/Example'

export default function Home() {
    const router = useRouter()
  console.log(router)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 className={styles.title}>
          <Link href="/Page2">
            <a>Page2</a>
          </Link>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <Example title="Card namber 1" description="Tu papa come aceitunas por el culo cuando duerme con un iptus"></Example>
        <Example title="Titulo 2" description="Saenz es una perra masoquista homosexual"></Example>

      </main>
    </div>
  )
}
